#!/bin/bash
if [[ -z "$@" ]]; then
  ARGS=(
    global.hub=istio
    global.tag=1.3.0
    global.imagePullPolicy=Always
    global.configValidation=false
    global.istioNamespace=istio-control
    global.configNamespace=istio-control
    sidecarInjectorWebhook.selfSigned=true
    sidecarInjectorWebhook.injectLabel=istio-env
    galley.mcpSinkAddress=meshconfig.googleapis.com:443
    sidecarInjectorWebhook.discoveryAddress=trafficdirector.googleapis.com:443
  )
else
  ARGS=("$@")
fi
for KV in "${ARGS[@]}"; do
  OVERRIDES+=(--set-string "${KV}")
done
SED=(sed 's/ *$//')
bin/iop istio-system citadel security/citadel -t "${OVERRIDES[@]}" | "${SED[@]}" > asm/citadel-gen.yaml
bin/iop istio-control istio-config istio-control/istio-config -t "${OVERRIDES[@]}" | "${SED[@]}" > asm/istio-config-gen.yaml
bin/iop istio-control istio-autoinject istio-control/istio-autoinject -t "${OVERRIDES[@]}" | "${SED[@]}" > asm/istio-autoinject-gen.yaml
bin/iop istio-control istio-discovery istio-control/istio-discovery -t "${OVERRIDES[@]}" | "${SED[@]}" > asm/istio-discovery-gen.yaml
