apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../crds
resources:
- namespace.yaml
- istio-asm-gen.yaml
configMapGenerator:
- name: asm-config
  namespace: istio-asm
  literals:
  - projectID=your-project-here
  - envoyAccessLogPath=/dev/stdout
